#!/bin/bash

containerNames=("template_laravel" "template_webserver" "template_db" "template_phpmyadmin")

for containerName in ${containerNames[*]}
do
	if docker ps -aq -f name=$containerName;
	then
		echo "Stopping ${containerName} container..."
		docker stop $containerName
		echo "Deleting ${containerName} container..."
		docker rm $containerName
	fi
done

docker run --rm -v $(pwd)/src/laravel:/app composer install
cd src/laravel/
cp .env.example .env.env 
mv .env.env .env
docker-compose up -d

echo -e "${color}
	  ==========================================
	   Open Laravel on  http://localhost:80
	  ==========================================
	   Open PHPmyadmin on http://localhost:8080
	  ==========================================
	   PHPmyadmin Credentials:
	   		Username -> user
	   		Password -> password
	  ==========================================
	 "
echo -e "${colorEnd}"